// <auto-generated />
using System;
using BásicoFacil.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BásicoFacil.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BásicoFacil.API.Entity.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Agua")
                        .HasColumnType("bit")
                        .HasColumnName("agua_potavel");

                    b.Property<bool>("Coleta")
                        .HasColumnType("bit")
                        .HasColumnName("coleta_lixo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<bool>("Drenagem")
                        .HasColumnType("bit")
                        .HasColumnName("drenagem");

                    b.Property<bool>("Esgoto")
                        .HasColumnType("bit")
                        .HasColumnName("rede_esgoto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("pontos")
                        .HasColumnType("int")
                        .HasColumnName("pontos");

                    b.HasKey("Id");

                    b.ToTable("Data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
